services:
  db:
    image: postgres:17
    restart: unless-stopped
    container_name: letsenroll-db
    env_file: ./config/.env
    ports:
      - "127.0.0.1:5430:5432" # So we can connect to it using an SSH tunnel via localhost:5430
    networks:
      - letsenroll
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    image: ghcr.io/freya022/letsenroll-api:latest
    restart: unless-stopped
    container_name: letsenroll-api
    networks:
      - letsenroll
      - caddy
    volumes:
      - ./config:/config
      - ./logs/api:/logs
  bot:
    image: ghcr.io/freya022/letsenroll-bot:latest
    restart: unless-stopped
    container_name: letsenroll-bot
    networks:
      - letsenroll
    volumes:
      - ./config:/config
      - ./logs/bot:/logs

networks:
  letsenroll: {}
  caddy:
    external: true

volumes:
  db-data: